name: Build Frontend (Vite)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set API URL
        run: echo "VITE_API_URL=https://yodha27-2.onrender.com" > .env

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yodha27-frontend-dist
          path: dist
