# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# flake8 is a python tool that glues together
# pycodestyle, pyflakes, mccabe, and third-party plugins
# to check the style and quality of some python code.
# More details at https://flake8.pycqa.org/

name: flake8

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ $default-branch ]
  schedule:
    - cron: $cron-weekly
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake8:
    name: Run flake8 scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install flake8
        run: |
          python -m pip install flake8
          python -m pip install flake8-sarif

      - name: Run flake8
        run: flake8 .
          --format=sarif
          --output-file=flake8-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: flake8-results.sarif
          wait-for-processing: true
