name: 'https://www.tiktok.com/@shoptify2?_r=1&_d=f1ikb72a2gj8f8&sec_uid=MS4wLjABAAAAF-Ud9BoBq1SYaTspej2FdcznFBkIJybtBOBEu0OIqQc0RGxJFjfyumF-STuc0iP3&share_author_id=7001223661772964869&sharer_language=en&source=h5_m&u_code=dkamacac7fm040&timestamp=1779915979&user_id=7001223661772964869&sec_user_id=MS4wLjABAAAAF-Ud9BoBq1SYaTspej2FdcznFBkIJybtBOBEu0OIqQc0RGxJFjfyumF-STuc0iP3&item_author_type=1&utm_source=copy&utm_campaign=client_share&utm_medium=android&share_iid=7632103918659962640&share_link_id=adbb8aac-0e8a-449f-8d45-02f161f83d6c&share_app_id=1233&ugbiz_name=ACCOUNT&ug_btm=b8727%2Cb7360&social_share_type=5&enable_checksum=1Auto Assign'
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:https://www.tiktok.com/@shoptify2?refer=creator_embed
      - uses: kentaro-m/auto-assign-action@v1.2.2
