name: Issue assignment

on:
    issues:
        types: [opened]

permissions:
  issues: write
  contents: read
  
jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1.11.0
              with:
                  assignees: edship
                  numOfAssignee: 1
