name: Composite action for greeting
on:
  # This adds the "Run workflow" button and the input popup
  workflow_dispatch:
    inputs:
      user_name:
        description: 'Who should I greet?'
        required: true
        default: 'World'
        type: string

jobs:
  greet_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Greeting
        uses: test-edship-org/github-actions-starter@main
        with:
          user_name: 'Gemini User'
