name: Composite action for greeting
on: [push, workflow_dispatch]

jobs:
  greet_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Greeting
        uses: test-edship-org/github-actions-starter@main
        with:
          user_name: 'Gemini User'
