name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:[![NodeJS with Gulp](https://github.com/Apostles1/Apostles-white-horse/actions/workflows/npm-gulp.yml/badge.svg?event=workflow_run)](https://github.com/Apostles1/Apostles-white-horse/actions/workflows/npm-gulp.yml)
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp
