on:
  push:
    branches:
    - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git config user.email "cschleiden@github.com"
        git config user.name "GitHub Actions"
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Check starter workflows for GHES compat
      run: |
        npm ci
        npx ts-node-script ./index.ts
      working-directory: ./script/sync-ghes
    - run: |
        git add -A
        
        git commit -m "Updating GHES workflows"
    - run: git push
